version: "3.3.1"
networks:
  hadoop:
    external: true
    name: hadoop
services:

  namenode:
      image: sequenceiq/hadoop-docker:2.7.1
      container_name: hadoop-namenode-standalone-3.3.1
      hostname: namenode
      ports:
        - "50070:50070"
        - "9000:9000"
        - "9870:9870"
        - "9864:9864"
    
      volumes:
        - ./hadoop-data/namenode:/hadoop/dfs/name
        - ./hadoop-data:/hadoop-data
      environment:
        - CLUSTER_NAME=docker-hadoop
        - HADOOP_USER_NAME=root
        - HADOOP_GROUP_NAME=root
        - PATH=$PATH:/usr/local/hadoop/bin:/usr/local/hadoop/sbin
        - ./config/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml
      networks:
        hadoop:


      command: /etc/bootstrap.sh -d namenode

  datanode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-datanode-standalone-3.3.1
    hostname: datanode
    volumes:
      - ./hadoop-data/datanode:/hadoop/dfs/data
      - ./hadoop-data:/hadoop-data
    #  - /home/nicholas/dev:/home/nicholas/dev
    environment:
      - CLUSTER_NAME=docker-hadoop
      - HADOOP_USER_NAME=root
      - HADOOP_GROUP_NAME=root
      - PATH=$PATH:/usr/local/hadoop/bin:/usr/local/hadoop/sbin
      - ./config/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml
    networks:
      hadoop:

  spark-master:
    image: cluster-apache-spark:3.3.1
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./jars/delta-core_2.12-2.3.0.jar:/opt/spark/jars/delta-core_2.12-2.3.0.jar
       - ./jars/ojdbc8.jar:/opt/spark/jars/ojdbc8.jar
       - ./jars/oraclepki-19.11.0.0.jar:/opt/spark/jars/oraclepki-19.11.0.0.jar
       - ./jars/oraclepki-19.11.0.0.jar:/opt/oracle/instantclient_19_19/oraclepki-19.11.0.0.jar
      # - /home/nicholas/dev:/home/nicholas/dev
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
      - SPARK_PUBLIC_DNS=localhost
    networks:
      hadoop:
  spark-worker-a:
    image: cluster-apache-spark:3.3.1
    ports:
      - "9091:8080"
      - "7001:7000"
      - "4041:4040"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      # - SPARK_WORKER_CORES=4
      # - SPARK_WORKER_MEMORY=8G
      # - SPARK_DRIVER_MEMORY=2G
      # - SPARK_EXECUTOR_MEMORY=8G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
      - SPARK_PUBLIC_DNS=localhost
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./jars/delta-core_2.12-2.3.0.jar:/opt/spark/jars/delta-core_2.12-2.3.0.jar
      # - /home/nicholas/dev:/home/nicholas/dev Local Mount
    networks:
        hadoop:
  # spark-worker-b:
  #   image: cluster-apache-spark:3.3.1
  #   ports:
  #     - "9092:8080"
  #     - "7001:7000"
  #     - "4042:4040"
  #   depends_on:
  #     - spark-master
  #   environment:
  #     - SPARK_MASTER=spark://spark-master:7077
  #     # - SPARK_WORKER_CORES=4
  #     # - SPARK_WORKER_MEMORY=8G
  #     # - SPARK_DRIVER_MEMORY=2G
  #     # - SPARK_EXECUTOR_MEMORY=8G
  #     - SPARK_WORKLOAD=worker
  #     - SPARK_LOCAL_IP=spark-worker-b
  #     - SPARK_PUBLIC_DNS=localhost
  #   volumes:
  #       - ./apps:/opt/spark-apps
  #       - ./data:/opt/spark-data
  #       - ./jars/delta-core_2.12-2.3.0.jar:/opt/spark/jars/delta-core_2.12-2.3.0.jar
  #       - /home/nicholas/dev:/home/nicholas/dev
  #   networks:
  #       hadoop:
  demo-database:
    image: postgres:11.7-alpine
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=casa1234
    networks:
        hadoop:

  